title: Dana Daskalova # your name (or website title) here
logo: "/images/pass-photo-b-w-small.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br> I'm a data scientist based in Bulgaria. Here you can see some of my passion projects! <br>
  <br> Main points of focus: data exploration and visualisation; preprocessing and cleaning. Advanced analystics such as regression and classification analysis, time series. <br>
  <a href="www.linkedin.com/in/dana-daskalova/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
